export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  FRONT_OFFICE: '/front-office',
  FRONT_OFFICE_VISITORS: '/front-office/visitors',
  FRONT_OFFICE_VISITORS_NEW: '/front-office/visitors/new',
  FRONT_OFFICE_ENQUIRIES: '/front-office/enquiries',
  FRONT_OFFICE_ENQUIRIES_NEW: '/front-office/enquiries/new',
  FRONT_OFFICE_APPOINTMENTS: '/front-office/appointments',
  FRONT_OFFICE_APPOINTMENTS_NEW: '/front-office/appointments/new',
  FRONT_OFFICE_APPOINTMENTS_CALENDAR: '/front-office/appointments/calendar',
  FRONT_OFFICE_COMPLAINTS: '/front-office/complaints',
  FRONT_OFFICE_COMPLAINTS_NEW: '/front-office/complaints/new',
  // Future routes will be added here
  // STUDENTS: '/students',
  // TEACHERS: '/teachers',
  // ATTENDANCE: '/attendance',
  // FEES: '/fees',
  // EXAMINATIONS: '/examinations',
  LIBRARY: '/library',
  LIBRARY_PERMISSIONS: '/library/permissions',
  LIBRARY_PERMISSIONS_NEW: '/library/permissions/new',
  LIBRARY_PERMISSIONS_EDIT: '/library/permissions/:id/edit',
  LIBRARY_ROLES: '/library/roles',
  LIBRARY_USERS: '/library/users',
  LIBRARY_CATEGORIES: '/library/categories',
  LIBRARY_CATEGORIES_NEW: '/library/categories/new',
  LIBRARY_CATEGORIES_EDIT: '/library/categories/:id/edit',
  LIBRARY_MEMBERSHIP_RULES: '/library/membership-rules',
  LIBRARY_MEMBERSHIP_RULES_NEW: '/library/membership-rules/new',
  LIBRARY_MEMBERSHIP_RULES_EDIT: '/library/membership-rules/:id/edit',
  // TRANSPORT: '/transport',
  // REPORTS: '/reports',
  // SETTINGS: '/settings',
} as const;
